/*
 * Watchman API
 *
 * Moov Watchman is an HTTP API and Go library to download, parse and offer search functions over numerous trade sanction lists from the United States, European Union governments, agencies, and non profits for complying with regional laws. Also included is a web UI and async webhook notification service to initiate processes on remote systems.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"time"
)

// OfacSearch struct for OfacSearch
type OfacSearch struct {
	// SDN EntityID of the Entity
	EntityID string `json:"entityID,omitempty"`
	// Name of the SDN entity
	SdnName string `json:"sdnName,omitempty"`
	// SDN entity type
	SdnType string `json:"sdnType,omitempty"`
	// Percentage of similarity between the Customer name and this OFAC entity
	Match     float32   `json:"match,omitempty"`
	CreatedAt time.Time `json:"createdAt,omitempty"`
}
